name: face_camera
description: A Flutter camera plugin that detects faces in real-time. In addition it can capture automatically once a face is detected, This can be handy while taking a selfie during kyc.
version: 0.0.19
homepage: https://github.com/K1yoshiSho/face_camera_plus.git

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+3
  google_mlkit_face_detection: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  plugin:
    platforms:
      android:
        package: com.conezi.face_camera
        pluginClass: FaceCameraPlugin
      ios:
        pluginClass: FaceCameraPlugin